export const ecosystemCategories = [
	{
		title: "Astria",
		category: ["Rollups", "Rollups-as-a-service", "Shared sequencer"],
		image: "ecosystem/astria.png",
		url: "https://astria.org/",
	},
	{
		title: "Alpha Dune",
		category: ["Rollups"],
		image: "ecosystem/alphadune.png",
		url: "https://alphadune.com/",
	},
	{
		title: "LightLink",
		category: ["Rollups"],
		image: "ecosystem/lightlink.png",
		url: "https://lightlink.io/",
	},
	{
		title: "Manta Network",
		category: ["Rollups"],
		image: "ecosystem/manta.png",
		url: "https://manta.network/",
	},
	{
		title: "AsMatch",
		category: ["Rollups"],
		image: "ecosystem/asmatch.png",
		url: "https://www.asmatch.app/",
	},
	{
		title: "Movement Labs",
		category: ["Rollups"],
		image: "ecosystem/movement.png",
		url: "https://movementlabs.xyz/",
	},
	{
		title: "Ojo",
		category: ["Rollups"],
		image: "ecosystem/ojo.png",
		url: "https://ojo.network/",
	},
	{
		title: "Deri",
		category: ["Rollups"],
		image: "ecosystem/deri.png",
		url: "https://deri.io/#/index",
	},
	{
		title: "Paima Engine",
		category: ["Infrastructure"],
		image: "ecosystem/paima.png",
		url: "https://paimastudios.com/",
	},
	{
		title: "Curio",
		category: ["Rollups"],
		image: "ecosystem/curio.png",
		url: "https://www.curio.gg/",
	},
	{
		title: "Pocket Network",
		category: ["Rollups"],
		image: "ecosystem/pocket.png",
		url: "https://www.pokt.network/",
	},
	{
		title: "Shogun",
		category: ["Rollups"],
		image: "ecosystem/shogun.png",
		url: "https://twitter.com/shogunfi/",
	},
	{
		title: "Eclipse",
		category: ["Rollups"],
		image: "ecosystem/eclipse.png",
		url: "https://www.eclipse.builders/",
	},
	{
		title: "Syndr",
		category: ["Rollups"],
		image: "ecosystem/syndr.png",
		url: "https://www.syndr.com/",
	},
	{
		title: "Hokum",
		category: ["Rollups"],
		image: "ecosystem/hokum.png",
		url: "https://hokum.gg/",
	},
	{
		title: "UniDex",
		category: ["Rollups"],
		image: "ecosystem/unidex.png",
		url: "https://www.unidex.exchange/",
	},
	{
		title: "Kinto",
		category: ["Rollups"],
		image: "ecosystem/kinto.png",
		url: "https://kinto.xyz/",
	},
	{
		title: "Zeko",
		category: ["Rollups"],
		image: "ecosystem/zeko.png",
		url: "https://zeko.io/",
	},
	{
		title: "ZKFair",
		category: ["Rollups"],
		image: "ecosystem/zkfair.png",
		url: "https://zkfair.io/",
	},
	{
		title: "Last L2",
		category: ["Rollups"],
		image: "ecosystem/lastl2.png",
		url: "https://golast.xyz/",
	},
	{
		title: "Dark Frontier",
		category: ["Rollups"],
		image: "ecosystem/darkfrontier.png",
		url: "https://darkfrontier.gg/",
	},
	{
		title: "Forma",
		category: ["Rollups"],
		image: "ecosystem/forma.png",
		url: "",
	},
	{
		title: "Caldera",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/caldera.png",
		url: "https://www.caldera.xyz/",
	},
	{
		title: "Vistara",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/vistara.png",
		url: "https://docs.vistara.dev/",
	},
	{
		title: "Snapchain",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/snapchain.png",
		url: "https://www.snapchain.dev/",
	},
	{
		title: "Altlayer",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/altlayer.png",
		url: "https://www.altlayer.io/",
	},
	{
		title: "Conduit",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/conduit.png",
		url: "https://conduit.xyz/",
	},
	{
		title: "Gateway",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/gateway.png",
		url: "https://gateway.fm/",
	},
	{
		title: "Gelato",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/gelato.png",
		url: "https://www.gelato.network/",
	},
	{
		title: "Lumoz",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/lumoz.png",
		url: "https://lumoz.org/",
	},
	{
		title: "Zeeve",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/zeeve.png",
		url: "https://www.zeeve.io/",
	},
	{
		title: "Karnot",
		category: ["Rollups-as-a-service"],
		image: "ecosystem/karnot.png",
		url: "https://www.karnot.xyz/",
	},
	{
		title: "Rollkit",
		category: ["Rollup framework"],
		image: "ecosystem/rollkit.png",
		url: "https://www.rollkit.dev/",
	},
	{
		title: "Sovereign SDK",
		category: ["Rollup framework"],
		image: "ecosystem/sovereign.png",
		url: "https://sovereign.xyz/",
	},
	{
		title: "OP Stack",
		category: ["Rollup framework"],
		image: "ecosystem/optimism.png",
		url: "https://docs.optimism.io/stack/getting-started",
	},
	{
		title: "Stackr",
		category: ["Rollup framework"],
		image: "ecosystem/stackr.png",
		url: "https://www.stackrlabs.xyz/",
	},
	{
		title: "Arbitrum Orbit",
		category: ["Rollup framework"],
		image: "ecosystem/arbitrum.png",
		url: "https://arbitrum.io/orbit",
	},
	{
		title: "Dymint",
		category: ["Rollup framework"],
		image: "ecosystem/dymension.png",
		url: "https://dymension.xyz/",
	},
	{
		title: "Polygon CDK",
		category: ["Rollup framework"],
		image: "ecosystem/polygoncdk.png",
		url: "https://polygon.technology/polygon-cdk",
	},
	{
		title: "Cartesi",
		category: ["Rollup framework", "Virtual machine"],
		image: "ecosystem/cartesi.png",
		url: "https://cartesi.io/",
	},
	{
		title: "Keystone",
		category: ["Rollup framework"],
		image: "ecosystem/curio.png",
		url: "https://www.keystonesdk.com/",
	},
	{
		title: "Radius",
		category: ["Shared sequencer"],
		image: "ecosystem/radius.png",
		url: "https://www.theradius.xyz/",
	},
	{
		title: "Fairblock",
		category: ["Shared sequencer"],
		image: "ecosystem/fairblock.png",
		url: "https://twitter.com/Fair_Block",
	},
	{
		title: "Madara",
		category: ["Shared sequencer"],
		image: "ecosystem/madara.png",
		url: "https://www.madara.zone/",
	},
	{
		title: "NodeKit",
		category: ["Shared sequencer"],
		image: "ecosystem/nodekit.png",
		url: "https://www.nodekit.xyz/",
	},
	{
		title: "Neutron",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/neutron.png",
		url: "https://neutron.org/",
	},
	{
		title: "Berachain",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/berachain.png",
		url: "https://berachain.com/",
	},
	{
		title: "Saga",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/saga.png",
		url: "https://www.saga.xyz/",
	},
	{
		title: "Dymension",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/dymension.png",
		url: "https://dymension.xyz/",
	},
	{
		title: "Osmosis",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/osmosis.png",
		url: "https://osmosis.zone/",
	},
	{
		title: "Initia",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/initia.png",
		url: "https://twitter.com/initiaFDN",
	},
	{
		title: "Argus",
		category: ["Settlement layer & bridging hubs"],
		image: "ecosystem/argus.png",
		url: "https://argus.gg/",
	},
	{
		title: "Axelar",
		category: ["Cross chain"],
		image: "ecosystem/axelar.png",
		url: "https://axelar.network/",
	},
	{
		title: "Hyperlane",
		category: ["Cross chain"],
		image: "ecosystem/hyperlane.png",
		url: "https://www.hyperlane.xyz/",
	},
	{
		title: "Catalyst",
		category: ["Cross chain"],
		image: "ecosystem/catalyst.png",
		url: "https://catalyst.exchange/",
	},
	{
		title: "Squid",
		category: ["Cross chain"],
		image: "ecosystem/squid.png",
		url: "https://www.squidrouter.com/",
	},
	{
		title: "Skip",
		category: ["Cross chain"],
		image: "ecosystem/skip.png",
		url: "https://skip.money/",
	},
	{
		title: "Mitosis",
		category: ["Cross chain"],
		image: "ecosystem/mitosis.png",
		url: "https://twitter.com/MitosisOrg",
	},
	{
		title: "Polyhedra",
		category: ["Cross chain"],
		image: "ecosystem/polyhedra.png",
		url: "https://polyhedra.network/",
	},
	{
		title: "Wormhole",
		category: ["Cross chain"],
		image: "ecosystem/wormhole.png",
		url: "https://wormhole.com/",
	},
	{
		title: "Union",
		category: ["Cross chain"],
		image: "ecosystem/union.png",
		url: "https://union.build/",
	},
	{
		title: "Orb Labs",
		category: ["Cross chain"],
		image: "ecosystem/orb.png",
		url: "https://www.orblabs.xyz/",
	},
	{
		title: "Celenium",
		category: ["Explorer"],
		image: "ecosystem/celenium.png",
		url: "https://celenium.io/",
	},
	{
		title: "Dora",
		category: ["Explorer"],
		image: "ecosystem/dora.png",
		url: "https://www.ondora.xyz/",
	},
	{
		title: "Mintscan",
		category: ["Explorer"],
		image: "ecosystem/mintscan.png",
		url: "https://www.mintscan.io/celestia",
	},
	{
		title: "Modular Cloud",
		category: ["Explorer"],
		image: "ecosystem/modularcloud.png",
		url: "https://explorer.modular.cloud/celestia-mainnet",
	},
	{
		title: "Numia",
		category: ["Analytics"],
		image: "ecosystem/numia.png",
		url: "https://www.numia.xyz/",
	},
	{
		title: "Range",
		category: ["Analytics"],
		image: "ecosystem/range.png",
		url: "https://www.range.org/",
	},
	{
		title: "Cosmostation",
		category: ["Wallet"],
		image: "ecosystem/cosmostation.png",
		url: "https://www.cosmostation.io/",
	},
	{
		title: "Keplr",
		category: ["Wallet"],
		image: "ecosystem/keplr.png",
		url: "https://www.keplr.app/",
	},
	{
		title: "Leap wallet",
		category: ["Wallet"],
		image: "ecosystem/leap-wallet.png",
		url: "https://www.leapwallet.io/",
	},
	{
		title: "Cosmology",
		category: ["Wallet"],
		image: "ecosystem/cosmology.png",
		url: "https://cosmology.tech/",
	},
	{
		title: "Aori",
		category: ["Infrastructure"],
		image: "ecosystem/aori.png",
		url: "https://www.aori.io/",
	},
	{
		title: "Noble",
		category: ["Infrastructure"],
		image: "ecosystem/noble.png",
		url: "https://nobleassets.xyz/",
	},
	{
		title: "Risc Zero",
		category: ["Infrastructure"],
		image: "ecosystem/risczero.png",
		url: "https://www.risczero.com/",
	},
	{
		title: "Marlin",
		category: ["Infrastructure"],
		image: "ecosystem/marlin.png",
		url: "https://www.marlin.org/",
	},
	{
		title: "Nebra",
		category: ["Infrastructure"],
		image: "ecosystem/nebra.png",
		url: "https://www.nebra.one/",
	},
	{
		title: "Redstone",
		category: ["Infrastructure"],
		image: "ecosystem/redstone.png",
		url: "https://redstone.finance/",
	},
	{
		title: "Privy",
		category: ["Wallet"],
		image: "ecosystem/privy.png",
		url: "https://www.privy.io/",
	},
	{
		title: "ZeroDev",
		category: ["Infrastructure"],
		image: "ecosystem/zerodev.png",
		url: "https://zerodev.app/",
	},
	{
		title: "Arc",
		category: ["Infrastructure"],
		image: "ecosystem/arc.png",
		url: "https://www.onarc.io/",
	},
	{
		title: "Polaris",
		category: ["Virtual machine"],
		image: "ecosystem/berachain.png",
		url: "https://berachain.com/",
	},
	{
		title: "CosmWasm",
		category: ["Virtual machine"],
		image: "ecosystem/cosmwasm.png",
		url: "https://cosmwasm.com/",
	},
	{
		title: "Nebula Garden",
		category: ["Rollups"],
		image: "ecosystem/nebulagarden.png",
		url: "https://twitter.com/NebulaGarden_",
	},
	{
		title: "Plume Network",
		category: ["Rollups"],
		image: "ecosystem/plumenetwork.png",
		url: "https://www.plumenetwork.xyz/",
	},
];
