export const pressData = {
	title: "Press & Media",
	text: "",
	items: [
        	{
			id: 1,
			title: "Branding",
			text: "",
			image: "press/branding.png",
			type: "external",
			figma: false,
			color: "#F3ECFF",
			url: "https://company-223625.frontify.com/d/JoSwaZS4Mjpj/guidelines",
		},
        	{
			id: 2,
			title: "Media kit",
			text: "",
			image: "press/media-kit.png",
			type: "external",
			figma: false,
			color: "#FFF2E1",
			url: "https://raw.githubusercontent.com/celestiaorg/celestia.org/main/src/images/press/Celestia_Labs_Media_Kit.pdf",
		},
        	{
			id: 3,
			title: "News",
			text: "",
			image: "press/news.png",
			type: "external",
			figma: false,
			color: "#DEF7FF",
			url: "https://blog.celestia.org/celestia-raises-55m-to-launch-modular-blockchain-network/",
		},
        	{
			id: 4,
			title: "Social channels",
			text: "",
			image: "press/social.png",
			type: "internal",
			figma: false,
			color: "#E7FFD4",
			url: "/community/",
		},
	],
};
